	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x10001000
	DCD Reset_Handler
	ALIGN
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	MOV R5,#55
	MOV R1,#12
LOOP 
	CMP R1,R5
	BPL GREATER
	BEQ STOP
	SUB R5,R5,R1
	CMP R1,R5
	BNE LOOP
	LDR R6,=RESULT
	STR R5,[R6]
STOP B STOP
GREATER 
	SUB R1,R1,R5
	B LOOP
	AREA mydata,DATA,READWRITE
RESULT DCD 0
	END
	